### ISSUE TITLE
Doesn't work with piko 7.0 anymore

### ISSUE THREAD

**Issue by britiger** [gieljnssns/KostalPikoPy#2]
It seams the the pull request I made has been removed:

https://github.com/gieljnssns/KostalPyko/pull/1

I get the following error:
```
  File "/.../lib/python3.7/site-packages/kostalpyko/kostalpyko.py", line 154, in get_l3_power
    return int(self._get_raw_content()[14])
```

**Comment by gieljnssns** [comment]
@britiger I don't know where this went wrong...
I'm still learning git...
